### PR TITLE
Adds summer school course

### LINKED ISSUE #2165: Review feature/branch summer-school-course before merge
Some text/links are placeholders. We should check everything before merge

### PR DESCRIPTION
**Pull request by y4izus**
Fix #2165

### CODE REVIEW

**Comment by y4izus** [comment]
This PR is not ready to merge, we have to take a look at this things:

- [ ] When going to the links at the end, we lose the page preview because it's sticky to the top of the section. @JRussellHuffman, @lerongil , @vabarbosa  , I think we should fix that before merge, but I would like to hear what do you think:

Captura de pantalla 2021-09-28 a las 10 15 56

Captura de pantalla 2021-09-28 a las 10 15 39

- [ ] Some links on the above section are not working:

- https://learn.qiskit.org/summer-school/2021/lec1-1-vector-spaces-tensor-products-qubits should be https://learn.qiskit.org/summer-school/2021/lec1-1-vector-spaces-tensor-products-and-qubits
- https://learn.qiskit.org/summer-school/2021/lec1-2-introduction-quantum-circuits should be https://learn.qiskit.org/summer-school/2021/lec1-2-introduction-to-quantum-circuits
- https://learn.qiskit.org/summer-school/2021/lec3-1-noise-quantum-computers-1 should be https://learn.qiskit.org/summer-school/2021/lec3-1-noise-in-quantum-computers-pt-1
- ... please, check everything

- [ ] On the prerequisite material section, the linear algebra link is pointing to the old textbook. We don't have (or at least I don't see) this section on the new textbook. Should we create that section on the new textbook or it's ok to point to the old one? @lerongil , @JRussellHuffman , @vabarbosa 
Captura de pantalla 2021-09-28 a las 10 34 59

**Comment by techtolentino** [comment]
following up with the URL comment:

The links in this PR are correct - they should remain.
To ensure they match with the platypus side, I made a PR _[there](https://github.com/qiskit-community/platypus/pull/156)_


Thank you for the extra layers of checking @y4izus

**Comment by vabarbosa** [comment]
> 
> * [ ]  When going to the links at the end, we lose the page preview because it's sticky to the top of the section. @JRussellHuffman, @lerongil , @vabarbosa  , I think we should fix that before merge, but I would like to hear what do you think:
> 

i would agree we should update the page so the preview image is not sticky to the top of the section

&nbsp;

> 
> * [ ]  On the prerequisite material section, the linear algebra link is pointing to the old textbook. We don't have (or at least I don't see) this section on the new textbook. Should we create that section on the new textbook or it's ok to point to the old one? @lerongil , @JRussellHuffman , @vabarbosa
>

we do have an intro to linear algebra in the new texbook, the link is: https://learn.qiskit.org/course/ch-appendix/an-introduction-to-linear-algebra-for-quantum-computing

--

CC @y4izus @techtolentino

**Comment by JRussellHuffman** [comment]
> On the prerequisite material section, the linear algebra link is pointing to the old textbook. We don't have (or at least I don't see) this section on the new textbook. Should we create that section on the new textbook or it's ok to point to the old one?

I don't want this to be a blocker, but this section should be created in the new textbook and we point to the new one. There shouldn't be any content in the old textbook that is not in the new textbook.  Can we ship the page with the current URL? Then, can we bring the page into the new textbook and update the URL to point to the new version?

**Review by eddybrando — APPROVED** [review]
Thanks a lot for this PR!

I added one small change.

We also need to wait for the PR #2193 to be merged into this feature branch.

**Comment by y4izus** [comment]
> we do have an intro to linear algebra in the new texbook, the link is: https://learn.qiskit.org/course/ch-appendix/an-introduction-to-linear-algebra-for-quantum-computing

@vabarbosa , I tried to look for that link but I didn't find it! can we access it from somewhere on learn.qiskit.org? it's not on the mega menu dropdown, not in the sections of the landing page, ...

**Comment by vabarbosa** [comment]
> @vabarbosa , I tried to look for that link but I didn't find it! can we access it from somewhere on learn.qiskit.org? it's not on the mega menu dropdown, not in the sections of the landing page, ...

@y4izus there is always the [sitemap.xml](https://learn.qiskit.org/sitemap.xml) or [sitemap.json](https://learn.qiskit.org/sitemap.json), which are a list of the available page links. in addition, there is the [toc.yaml](https://github.com/qiskit-community/platypus/blob/main/notebooks/toc.yaml) which is the list of notebooks that should be converted and made available. 

comparing with those, it appears the megamenu is missing the **Appendix** chapter which contains two sections:

- [An Introduction to Linear Algebra for Quantum Computing](https://learn.qiskit.org/course/ch-appendix/an-introduction-to-linear-algebra-for-quantum-computing)
- [Basic Qiskit Syntax](https://learn.qiskit.org/course/ch-appendix/basic-qiskit-syntax)

why the **Appendix** chapter (and those two sections) is not included in the megamenu i am not sure.

**Pull request merged**
