### PR TITLE
fix: hide advocate handle if not provided

### LINKED ISSUE #1940: [Advocates Page Content] Typo error on slack IDs of advocates on https://qiskit.org/advocates/
### Where is the problem?

https://qiskit.org/advocates/

### What is the problem?

In this page the slack IDs of the following advocates is having an error:

 Almudena Carrera Vazquez (no id given)
 Ana Martin (no id given)
 David Ittah (no id given)
 Desiree Vogt-Lee (no id given)
 Eesh Gupta( it is \@Quintiii not \@Quintiiii)
 Henrik Dreyer (no id given)
 Ismail Yunus Akhalwaya (no id given)
 Karel Dumon (no id given)
 Kohei Souji (wrong id )
 Mathew Treinish (no id given)
 Michele Grossi (no id given)
 Miguel Parades Quinones (no id given)
 Mohammed Ghazi Vakili (no id given)
 Pauline Ollitrault (no id given)
 Pedro Rivero Ramirez (no id given)
 Sasha Lazarevic (no id given)
 Yael Ben- Hain (no id given)
 Yehuda Naveh (no id given)

For example:
IMG_20210702_151246

### What would you expect?

Correct the error on Slack IDs of those Advocates listed above!

### PR DESCRIPTION
**Pull request by yoshiemuranaka**
## Changes
If advocates slack handle not provided, hide the slack icon and `@` symbol

Resolves #1940

## How to read this PR

Before 
Screenshot 2023-04-24 at 11 23 32 AM

After
Screenshot 2023-04-24 at 11 23 19 AM

### CODE REVIEW

**Comment by eddybrando** [comment]
@y4izus, I'm adding the _On Hold_ label so that we can check first the previous conversations around this topic as discussed.

**Comment by y4izus** [comment]
I have already checked it and the changes on the PR are valid, so I'm gonna remove the On Hold tag so we can review it :D

**Review by eddybrando — CHANGES_REQUESTED** [review]
Thanks for the PR @yoshiemuranaka!

This works fine in terms of hiding the Slack username data when it's not available, but it also results in a variation of the bottom spacing.

When we have the Slack username, the last element (the Slack username) doesn't add any additional spacing at the bottom:

Screenshot 2023-05-08 at 16 02 58

Now, when we don't have the Slack username, the last element is the location data, which adds a bottom margin and results in more space at the bottom of the card:

Screenshot 2023-05-08 at 16 03 21

Side by side:

image

A suggestion I can quickly come up with is using `margin-top` instead of `margin-bottom` in those elements.

**Review by techtolentino — DISMISSED** [review]
I like this solution, and I think it's the best approach until we hear further on any Advocates page details.

@y4izus @eddybrando - agree?

**Review by eddybrando — APPROVED** [review]
Looks great! Thank you @yoshiemuranaka!

**Pull request merged**
