### PR TITLE
Updating items on Infinite scroll now update observed data for ScrollSectionsMixin

### PR DESCRIPTION
**Pull request by korgan00**

### CODE REVIEW

**Review by eddybrando — CHANGES_REQUESTED** [review]
Thanks for the update @korgan00, but I’m afraid I could still see some issues when integrating this change to the advocates filter.

### Current behaviour:

- Checking “Australia” and “Africa” displays 2 advocates.

### Expected behaviour:

- Checking “Australia” and “Africa” should display 8 advocates (after some navigation).

### Steps to reproduce:

1. Check “Australia”
2. Navigate to the “events” page
3. Navigate to the “advocates” page
4. Check also “Africa”

### Additional information:

The Vuex store is calculating the 8 filtered advocates and passing these to the child component to render the cards properly.

**Comment by korgan00** [comment]
> Thanks for the update @korgan00, but I’m afraid I could still see some issues when integrating this change to the advocates filter.
> 
> ### Current behaviour:
> * Checking “Australia” and “Africa” displays 2 advocates.
> 
> ### Expected behaviour:
> * Checking “Australia” and “Africa” should display 8 advocates (after some navigation).
> 
> ### Steps to reproduce:
> 1. Check “Australia”
> 2. Navigate to the “events” page
> 3. Navigate to the “advocates” page
> 4. Check also “Africa”
> 
> ### Additional information:
> The Vuex store is calculating the 8 filtered advocates and passing these to the child component to render the cards properly.

Good catch! I made some other variables update. You can try it again.

**Review by eddybrando — APPROVED** [review]
Thank you @korgan00! 🙂 

I just gave it a try integrating it with the new advocates filter and the issue that I reported before seems to be gone.

Nice work 👍

**Review by y4izus — APPROVED** [review]
Thank you very much!

**Pull request merged**
