### PR TITLE
Updates data table content on QC40 page

### PR DESCRIPTION
**Pull request by y4izus**
Content update requested by the event's team. Waiting for the event's team review. DO NOT MERGE

### CODE REVIEW

**Review by eddybrando — APPROVED** [review]
LGMT!

**Important:** We still need a review from the events team before merging.

**Comment by y4izus** [comment]
I've created [another PR](https://github.com/Qiskit/qiskit.org/pull/1732) because I have more suggestions on styles. When they decided which one they prefer I will close the other PR

**Review by eddybrando — APPROVED** [review]
LGTM!

**Comment by y4izus** [comment]
We continue in the other PR, I'll close this one

**Pull request closed without merging**
