### PR TITLE
Ecosystem page 

### PR DESCRIPTION
**Pull request by javabster**
Add Qiskit ecosystem page

To do:

- [x] Add vuex store 
- [x] refactor `MemberCard` component (put logic into utils maybe?)
- [x] fix typescript warnings
- [x] add navbar button?
- [x] ✨ make it pretty ✨ 
- [x] tests 🧪 
- [x] add tracking to CTA links

### CODE REVIEW

**Comment by javabster** [comment]
Progress update:
- Added tabs for main vs community projects
- Test tables now pull in real data (if there is no test data for a certain repo the table doesn't show)

Screenshot 2021-11-17 at 15 11 14
Screenshot 2021-11-17 at 15 11 28

**Comment by javabster** [comment]
after discussion with @IceKhan13 I've done the following:
- rearranged the table data, so now just 1 row per version
- replaced the tabs with a basic checkbox filter
- added hardcoded example data for styles and coverage tests

Screenshot 2021-11-18 at 17 36 06
Screenshot 2021-11-18 at 17 36 27

**Comment by javabster** [comment]
screencapture-localhost-3000-ecosystem-2022-02-04-20_01_39
Screenshot 2022-02-04 at 8 02 15 PM

**Comment by JRussellHuffman** [comment]
Updated designs here, including a prototype screen for this page to show how the show/hide should work [here](https://www.figma.com/proto/N34caXM86bY1778Whk1c31/2503-ecosystem-page?page-id=64%3A3953&node-id=64%3A9445&viewport=241%2C48%2C0.27&scaling=min-zoom&starting-point-node-id=64%3A9445). (everyone should have access to this link)
I also drew up all the breakpoints for the page [here](https://www.figma.com/file/N34caXM86bY1778Whk1c31/2503-ecosystem-page?node-id=64%3A5897).

**Comment by javabster** [comment]
Progress update:

Screenshot 2022-04-18 at 4 51 00 PM

screencapture-localhost-3000-ecosystem-2022-04-18-16_50_13

**Comment by JRussellHuffman** [comment]
I'm just going to add my design 2 cents worth here:
It looks like the purple in the pills isn't quite the Qiskit purple. It should be #6929C4, and the screenshot appears to be #6035BD. I would also increase the spacing between the pills a little bit, I recommend 8 pixels in between total.
Lastly, the status icons will be a lot more effective if color-coded (you might be still working on this, but just wanted to write it out just in case).

**Comment by javabster** [comment]
Thanks for the comments @JRussellHuffman! Response below:

> It looks like the purple in the pills isn't quite the Qiskit purple. It should be #6929C4, and the screenshot appears to be #6035BD. 

I reused the same app card component that we use elsewhere on qiskit.org so the colour should match what we have for the tags on other pages e.g. events. Looking at the style code it's using purple-70, which is used in a lot of other places as well. Is this not correct?

> I would also increase the spacing between the pills a little bit, I recommend 8 pixels in between total. 

will do!

> Lastly, the status icons will be a lot more effective if color-coded (you might be still working on this, but just wanted to write it out just in case).

Yeah this was still WIP when i posted the last screenshot. It took a bit of refactoring from Yaiza and Goyo before we could get the icons to change colour and my last push now has the different colours. will post more screenshots shortly

**Comment by javabster** [comment]
screencapture-localhost-3000-ecosystem-2022-05-06-15_10_38

**Comment by JRussellHuffman** [comment]
Apologies, this thread got buried for me.

**Re: purple-70.** This might just be how my browser renders a color. If the component says purple-70, then I'm sure it's fine.

**Re: status icon.** The updated screenshot looks good to me!

**Review by eddybrando — APPROVED** [review]
Thanks a lot @javabster! This is looking great! 🙂

I added a couple of changes:

- Segment tracking
- Filter for small viewports
- Fixes in DOM tree and prop validation

**Comment by JRussellHuffman** [comment]
Hey everyone, I noticed a small issue in production. There should be a gray line separating the "ecosystem" and "advocates" tabs. It should be the same as how the "events" and "advocates" is separated by a line.

Screen Shot 2022-05-27 at 9 59 53 AM

**Comment by javabster** [comment]
> Hey everyone, I noticed a small issue in production. There should be a gray line separating the "ecosystem" and "advocates" tabs. It should be the same as how the "events" and "advocates" is separated by a line.
> 
> Screen Shot 2022-05-27 at 9 59 53 AM

I addressed this in one of my earlier commits that `components/layouts/TheMenu/index.vue` but it looks like that change got lost :/ @eddybrando i'm not sure what happened with the commit history and I'm on holiday right now can you sort this out please?

the change i made that i have locally is line342:
```
    // using pseudo element to achieve partial underline
    &:nth-last-child(n+2)::after {
      content: '';
      border-bottom: 1px solid $cool-gray-30;
      position: absolute;
      width: 80%;
      left: 10%;
      bottom: 0;
    }
```

**Comment by JRussellHuffman** [comment]
thank you!

**Pull request merged**
