### PR TITLE
Content fixes

### LINKED ISSUE #1069: Qiskit Metal text improvements
### Steps to reproduce the problem
Got to qiskit.org/metal

### What is the current behavior?
This issue is to call out grammatical and spelling errors and feedback from a content specialist.

### What is the expected behavior?

Capitalize Python in 2 places and remove the comma after Simply
Screen Shot 2020-10-16 at 1 09 56 PM

remove extra space after parens
Screen Shot 2020-10-16 at 1 11 48 PM

Remove the word “to”
Screen Shot 2020-10-16 at 1 13 09 PM

“Metal helps bridge” or “Metal bridges”.  Change ampersands to and.  Capitalize Metal.
Screen Shot 2020-10-16 at 1 14 47 PM

“and that we are developing” is awkward
Screen Shot 2020-10-16 at 1 16 49 PM

comma after teaching
Screen Shot 2020-10-16 at 1 18 44 PM

Something is missing in this sentence…
Screen Shot 2020-10-16 at 1 19 48 PM

### PR DESCRIPTION
**Pull request by korgan00**
Fix #1069

### CODE REVIEW

**Comment by korgan00** [comment]
Do not merge this yet.

**Review by techtolentino — APPROVED** [review]
These are great, thanks!

**Comment by JRussellHuffman** [comment]
Regarding the questions in #1069 

@korgan00 For the “and that we are developing” sentence:

    "Metal utilizes quantization methods and techniques from both the community and our own development."

For the "something is missing" sentence:

    "We hope to form this software into something that is usable by superconducting quantum hardware designers across industry and academia, and perhaps even for other qubit architectures."

**Comment by JRussellHuffman** [comment]
Looked over everything else. It all looks good to me!

**Review by techtolentino — APPROVED** [review]
Gave a 2nd review, this looks good...

**Pull request merged**
