### PR TITLE
QML overview page

### PR DESCRIPTION
**Pull request by vabarbosa**
this PR is to merge the QML overview page (for Textbook beta) from the feature branch into the main branch

Preview: https://qiskit-org-pr-2421.dcq4xc5i083.us-south.codeengine.appdomain.cloud/textbook-beta/

Related:
- https://github.com/Qiskit/qiskit.org/issues/2305
- https://github.com/Qiskit/qiskit.org/issues/2304
- https://github.com/Qiskit/qiskit.org/issues/2407

### CODE REVIEW

**Comment by vabarbosa** [comment]
@frankharkins @JRussellHuffman i believe this is good to go. we proceed with merging this afternoon (after https://github.com/Qiskit/platypus/pull/173 is merged)?

**Review by techtolentino — APPROVED** [review]
LGTM 🚀

**Comment by JRussellHuffman** [comment]
And here's my 👍 here as well.

**Review by techtolentino — APPROVED** [review]
🚢

**Pull request merged**
