### PR TITLE
Added button for Aqua GUI

### LINKED ISSUE #144: Add Github button and Install section for Aqua GUI
As Aqua's GUI has been extracted out as a separate repo/package, the GUI section of the Aqua page likely needs the following two elements:

- A Github button pointing to `https://github.com/Qiskit/qiskit-aqua-interfaces`

- An `Install` section for `pip install qiskit-aqua-interfaces`

### PR DESCRIPTION
**Pull request by carlosazaustre**
## Summary
Added the github repo button for Qiskit Aqua Chemistry GUI, following the style lines of the other sections.

image

## Comments
This PR closes #144

### CODE REVIEW

**Comment by hushaohan** [comment]
@carlosazaustre thx!

but this isn't exactly right. please refer to https://github.com/Qiskit/qiskit.org/issues/144#issuecomment-503637528

so basically:

- the current content under `Install` should actually be labeled as `Example` or `Invocation`;
- the actual content under `Install` should be
```
[python3] $ pip install qiskit-aqua-interfaces
```

please let me know if this isn't clear

**Comment by carlosazaustre** [comment]
Thx for the feedback @hushaohan :)
Is it correct?

image

**Comment by carlosazaustre** [comment]
Thanks for the feedback @hushaohan !

It is correct?
image

**Comment by hushaohan** [comment]
@carlosazaustre looks good, thx!

**Pull request merged**
