### PR TITLE
fix: adjust text color to improve accessibility

### LINKED ISSUE #1206: text color for quick start widget
### Steps to reproduce the problem
Just noticed the text color in the quick start widget (on the homepage and overview page) may have some slight accessibility issues. 

### What is the current behavior?
Current color is #6f6f6f 

### What is the expected behavior?
The text should be cool gray 80 (#343A3F)

### PR DESCRIPTION
**Pull request by eddybrando**
This PR changes the text colors `#6f6f6f` to `#343A3F` (_cool gray 80_) to improve accessibility.

---

Closes #1206

### CODE REVIEW

**Comment by eddybrando** [comment]
@JRussellHuffman, I replaced the occurrences of `#6f6f6f`, but I also realised that we have some code snippets in `#697077` which may also have too little contrast (please refer to the text marked in red in screenshot bellow)

Please let me know if that also needs to be changed. Maybe if not for accessibility, for visual consistency across similar UI elements, since the larger code snippet (marked in green in the screenshot bellow) uses a different gray text color (now `#343A3F`).

Screenshot 2021-01-04 at 16 43 59

**Comment by JRussellHuffman** [comment]
@eddybrando Good catch. The #697077 value is cool-gray-60, which technically passes accessibility on that background (cool-gray-10), but for consistency across UI elements, it should be changed to match the rest at cool-gray-80. I'll update the designs in figma too.

**Comment by eddybrando** [comment]
Thanks for the feedback @JRussellHuffman! 🙂

I've just adjusted the instances of `#697077`.

This PR is ready for review. 🙂

**Review by y4izus — APPROVED** [review]
Thank you very much Eddy!!

**Pull request merged**
