### PR TITLE
add primitives category

### PR DESCRIPTION
**Pull request by HuangJunye**
## Changes

- Added new `primivites.json`
- Added a new section `Native Primitives` in providers page
- Removed `Quantum Runtimes` category
- Added missing `Transpiling` example for qiskit-ibm-runtime

### CODE REVIEW

**Comment by HuangJunye** [comment]
@1ucian0 can we remove runtime category and only use primitives category if you are ok with that. I can update the PR once the decision is made.

**Comment by 1ucian0** [comment]
Sounds good!

**Comment by HuangJunye** [comment]
@1ucian0 I removed runtime section and added transpiling code example for qiskit-ibm-runtime for quick start. I think the PR is ready for review.

**Review by techtolentino — APPROVED** [review]
Just reviewed this code locally, nicely done @HuangJunye 

👏🏼

**Pull request merged**
