### PR TITLE
[WIP] Start implementing the announcement of Qiskit Optimization

### LINKED ISSUE #490: Update Aqua element for upcoming release
- [x] 1. Update new section with release copy + blog link

- [x] 2. Translators -> Applications, Core algorithms -> Aqua core algorithms & link 

- [x] 3. AI -> ML

- [x] 4. Add optimization section to mimic the about and example portion 

Due Date: 4/29/20

### PR DESCRIPTION
**Pull request by delapuente**
Fix #490

### CODE REVIEW

**Comment by delapuente** [comment]
This should be a draft, it is not complete. Please, do not merge!

**Comment by delapuente** [comment]
> What happens with the "kids meet quantum" block? Do we just remove it?

I think we should rotate the news. @lerongil any thoughts on this ☝️ ?

**Comment by lerongil** [comment]
> > What happens with the "kids meet quantum" block? Do we just remove it?
> 
> I think we should rotate the news. @lerongil any thoughts on this ☝️ ?

Let's plan on removing this. I do not see the /activity/ path in amplitude to see how accepted this is. @y4izus do you see it?

**Comment by y4izus** [comment]
> Let's plan on removing this. I do not see the /activity/ path in amplitude to see how accepted this is. @y4izus do you see it?

The kid's activity is shared in two different ways (directly on from the website and with a short link created by Anamita). So, to see how accepted it is, we should look in two places:
- We should talk with Anamita because in social media they are sharing the short link and she told me this way she could track the acceptance of it
- In Amplitude we can see the number of times people click on the button placed in the home page (430 for the last 30 days)

**Comment by delapuente** [comment]
After removing the elements, this is no longer valid. Closing.

**Pull request closed without merging**
