### PR TITLE
Parallelize jobs in GitHub Actions

### LINKED ISSUE #1172: Parallelize jobs in GitHub Actions
I think we could parallelize the GitHub Actions jobs; we would save a little time and the logs would be somewhat clearer.

### PR DESCRIPTION
**Pull request by abdonrd**
Fix #1172

If we merge it, we should [update the **`Required`** checks](https://github.com/Qiskit/qiskit.org/settings/branches):

Screenshot 2020-12-01 at 12 25 21

### CODE REVIEW

**Review by korgan00 — APPROVED** [review]
Sounds good ;)

**Comment by delapuente** [comment]
@abdonrd I'm assuming we are removing the cache mechanism cause we do not longer need to reuse the same `npm_folder`, right? Also, why do not we lint for node 12?

**Comment by abdonrd** [comment]
> @abdonrd I'm assuming we are removing the cache mechanism cause we do not longer need to reuse the same `npm_folder`, right? Also, why do not we lint for node 12?

Yes!

About the linting, I have assumed doing it on a single node version is enough.

**Review by delapuente — COMMENTED** [review]
Nice done. Thank you.

**Pull request merged**
