### PR TITLE
Revert deletion of logo in f87d2cc937639f5ff4fd4ce7d1bbaa691e2c6af8

### LINKED ISSUE #1135: Qiskit logo broken on the textbook
### Steps to reproduce the problem

Go to https://qiskit.org/textbook/preface.html

### What is the current behavior?
Browsers shows a broken image icon.
Screen Shot 2020-11-20 at 3 54 19 PM

### What is the expected behavior?
The header is currently out of date on the textbook anyway. Can we take this opportunity to update the header to match the rest of Qiskit.org?

### PR DESCRIPTION
**Pull request by eddybrando**
Restores deleted logo image file which was still in use in this repository's README and in the textbook website.

---

Bug introduced in f87d2cc937639f5ff4fd4ce7d1bbaa691e2c6af8 with merge 0e19b00ee2a8595518179cfb780e89e6d777217b.

---

Fixes #1135 and #1136

### CODE REVIEW

**Review by techtolentino — CHANGES_REQUESTED** [review]
Thanks for fixing this, @eddybrando.

Can you please include the `qiskit-new-logo-purple.svg` as well? That's the missing one in the [Textbook](https://qiskit.org/textbook/preface.html) I believe.


Thanks!

**Review by vabarbosa — COMMENTED** [review]
the textbook is actually linking to a different file/image: 

- https://qiskit.org/images/qiskit-new-logo-purple.svg

fyi, i [submitted a PR in textbook](https://github.com/qiskit-community/qiskit-textbook/pull/838) to use the actual SVG image instead of linking to a file in qiskit.org

**Comment by techtolentino** [comment]
> fyi, i [submitted a PR in textbook](https://github.com/qiskit-community/qiskit-textbook/pull/838) to use the actual SVG image instead of linking to a file in qiskit.org

If that's the case, disregard my comment... thanks for handling it on the Textbook side @vabarbosa

**Review by techtolentino — APPROVED** [review]

**Review by y4izus — APPROVED** [review]
Thank you very much!

**Pull request merged**
