### PR TITLE
feat(segment): new Segment properties structure

### LINKED ISSUE #1511: Create reusable definitions of segments actions' names for tracking
The tracking segment actions consist of long strings which can be broken down into reusable pieces in the form of constants.

This will help with future maintenance as well as providing a general overview of the labels we're using across the project.

### PR DESCRIPTION
**Pull request by eddybrando**
This PR updates the structure of the data passed to Segment via the _properties_.

---

Closes #1511

### CODE REVIEW

**Comment by eddybrando** [comment]
Moving this to "draft" to investigate an issue with some tracking events being sent multiple times.

**Comment by eddybrando** [comment]
@y4izus as discussed offline, regarding the multiple tracking events, I believe this is caused locally due to Segment retrying the failing requests, but I believe this is not exclusive to the implementation in the Textbook Beta, but just the general behaviour it has in the whole project when ran locally.

**Review by techtolentino — APPROVED** [review]
This looks great, @eddybrando 

And thanks for the follow-up to your conversation with @y4izus. 


One question I had: do you have screenshots or examples of what these _multiple tracking events_ looked like?

**Comment by eddybrando** [comment]
> This looks great, @eddybrando
> 
> And thanks for the follow-up to your conversation with @y4izus.
> 
> One question I had: do you have screenshots or examples of what these _multiple tracking events_ looked like?

Sure, @techtolentino!

Here are a couple of screenshots. This happens when you are running the project locally via the `npm run dev-analytics` script, go to the http://localhost:3000/textbook-beta/course/introduction-course page and click on the CTA in red:

image

image

The `t` network events are the tracking events. They keep popping up since the events keep retrying after failing.

**Review by y4izus — APPROVED** [review]
Thank you very much Eddy! this refactor will be very helpful!

**Pull request merged**
