### PR TITLE
Add Early access section

### LINKED ISSUE #997: Break off Early Access into its own section
The Early Access needs its own section.

### LINKED ISSUE #998: Add Education paragraph to "keep in touch section"
There's a new paragraph to add to the "keep in touch section" - see latest design for content and links.

### PR DESCRIPTION
**Pull request by techtolentino**
Fixes #997 (Early access section)
Fixes #998 (Adds Education content)

### CODE REVIEW

**Review by y4izus — CHANGES_REQUESTED** [review]
Good job! Just one thing: on a small screen, both text and button should have the same width as the screen

**Comment by techtolentino** [comment]
Great catch @y4izus - thanks.

We'll need to also update the Request early access button further up the dark page.

🙏

**Review by y4izus — CHANGES_REQUESTED** [review]
You still have the `max-width` set for texts in the two sections

**Comment by techtolentino** [comment]
@y4izus - okay, I fixed `max-width`s on small

**Pull request merged**
