### PR TITLE
Fix quickstart code examples

### PR DESCRIPTION
**Pull request by HuangJunye**
## Changes

Supersed https://github.com/Qiskit/qiskit.org/pull/3144. I forgot that we need to make PR from a branch instead of a fork to trigger preview workflow.

- Merged Rigetti and  Rigetti Quantum Virtual Machine entry in the same spirit of merging qiskit-ibm-provider and qiskit-ibm-runtime
- Update IBM Quantum token comment and code line, addressing https://github.com/Qiskit/qiskit.org/pull/3044#discussion_r1171192736

### CODE REVIEW

**Comment by HuangJunye** [comment]
Preview workflow failed due to this error https://github.com/Qiskit/qiskit.org/actions/runs/4745247568/jobs/8427286828#step:11:605

```
ERROR: denied: Your account has exceeded its image storage quota for the current month. See https://cloud.ibm.com/docs/Registry?topic=Registry-troubleshoot-quota
Error: buildx failed with: ERROR: denied: Your account has exceeded its image storage quota for the current month. See https://cloud.ibm.com/docs/Registry?topic=Registry-troubleshoot-quota
```

Any idea how to fix it (if we need to fix it at all)?

**Review by techtolentino — APPROVED** [review]
This LGTM @HuangJunye - thank you

🚀

**Comment by HuangJunye** [comment]
> This LGTM @HuangJunye - thank you
> 
> 🚀
> 
> Non-blocking question: should the same comment be included in the Providers page list, under the [hardware yaml](https://github.com/Qiskit/qiskit.org/blob/fix-quickstart-code-examples/content/providers/list/2.hardware.yaml#L44-L45)?

Yes, good catch! Let me make the changes in the providers yaml as well.

**Comment by HuangJunye** [comment]
Fixed in https://github.com/Qiskit/qiskit.org/pull/3145/commits/49b0dc00996ec9fc42b2b1b5f3aea2c2944fa123 @techtolentino Can you please have another look? Thanks!

**Pull request merged**
